services:
  mysql-db-inventory:
    image: mariadb:10.6
    container_name: mysql-db-inventory
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: inventory-db
      MYSQL_USER: kounet
      MYSQL_PASSWORD: 1234
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 11
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9999:80
    environment:
      PMA_HOST: mysql-db-inventory
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
  inventoryservices:
    build: ./inventoryservices
    container_name: inventoryservices
    ports:
      - '8098:8098'
    expose:
      - '8098'
    restart: always
    depends_on:
      - mysql-db-inventory
    environment:
      - DB_URL=jdbc:mysql://mysql-db-inventory:3306/inventory-db
  postgres-service:
    image: postgres
    container_name: postgres-service
    volumes:
      - postgres_data_kounet:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak_kounet_db
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: k1234
    ports:
      - '5432:5432'
    expose:
      - '5432'
    healthcheck:
      test: "exit 0"
  pgadmin:
      image: dpage/pgadmin4:latest
      container_name: pgadmin4
      restart: always
      ports:
        - "8888:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: kounet@gmail.com
        PGADMIN_DEFAULT_PASSWORD: 1234
      volumes:
        - pgadmin_data:/var/lib/pgadmin
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      environment:
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://postgres-service:5432/keycloak_kounet_db
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: k1234
        KEYCLOAK_ADMIN: admin
        KC_HTTP_ENABLED: "true"
        KC_HOSTNAME_STRICT_HTTPS: "false"
        KEYCLOAK_ADMIN_PASSWORD: admin
      command:
        - start-dev
      restart: always
      ports:
        - '8080:8080'
      expose:
        - '8080'
      depends_on:
        - postgres-service
  mvctemplet:
      image: mvctemplet
      build: ./mvctemplet
      container_name: mvctemplet
      ports:
        - '8093:8093'
      expose:
        - '8093'
      restart: always
      depends_on:
        - keycloak
      environment:
        - KEYCLOAK_REDIRECT_URI=http://localhost:8090/login/oauth2/code/customer-client
        - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/customer-client
volumes:
  mysql_data:
  postgres_data_kounet:
  pgadmin_data:
